UPDATE products SET door_count = 2, name = 'Boss 80x220 Walnut' WHERE sku = 'CAB-MNM-0058';
UPDATE products SET door_count = 4, name = 'Boss 160x220 White' WHERE sku = 'CAB-MNM-0059';
UPDATE products SET door_count = 4, name = 'Boss 160x220 Cashmere' WHERE sku = 'CAB-MNM-0060';
UPDATE products SET door_count = 4, name = 'Boss 160x220 Walnut' WHERE sku = 'CAB-MNM-0061';
UPDATE products SET door_count = 4, name = 'Boss 180x220 White' WHERE sku = 'CAB-MNM-0062';
UPDATE products SET door_count = 4, name = 'Boss 180x220 Cashmere' WHERE sku = 'CAB-MNM-0063';
UPDATE products SET door_count = 4, name = 'Boss 180x220 Drawers Walnut' WHERE sku = 'CAB-MNM-0064';
UPDATE products SET door_count = 4, name = 'Boss 180x220 Drawers White' WHERE sku = 'CAB-MNM-0065';
UPDATE products SET door_count = 3, name = 'Boss 120x220 Drawers Cashmere' WHERE sku = 'CAB-MNM-0066';
UPDATE products SET door_count = 2, name = 'Boss 90x220 Drawers Walnut' WHERE sku = 'CAB-MNM-0067';
UPDATE products SET door_count = 3, name = 'Boss 120x220 Drawers Walnut' WHERE sku = 'CAB-MNM-0068';
UPDATE products SET door_count = 3, name = 'Boss 120x220 White' WHERE sku = 'CAB-MNM-0069';
UPDATE products SET door_count = 3, name = 'Boss 120x220 Cashmere' WHERE sku = 'CAB-MNM-0070';
UPDATE products SET door_count = 3, name = 'Boss 120x220 Walnut' WHERE sku = 'CAB-MNM-0071';
UPDATE products SET door_count = 2, name = 'Boss 90x220 Drawers White' WHERE sku = 'CAB-MNM-0072';
UPDATE products SET door_count = 2, name = 'Boss 90x220 Drawers Cashmere' WHERE sku = 'CAB-MNM-0073';
UPDATE products SET door_count = 2, name = 'Boss 90x220 White' WHERE sku = 'CAB-MNM-0074';
UPDATE products SET door_count = 4, name = 'Boss 160x220 Drawers Walnut' WHERE sku = 'CAB-MNM-0075';
UPDATE products SET door_count = 2, name = 'Boss 90x220 Cashmere' WHERE sku = 'CAB-MNM-0076';
UPDATE products SET door_count = 2, name = 'Boss 90x220 Walnut' WHERE sku = 'CAB-MNM-0077';
UPDATE products SET door_count = 3, name = 'Boss 135x220 Drawers White' WHERE sku = 'CAB-MNM-0078';
UPDATE products SET door_count = 3, name = 'Boss 135x220 Drawers Cashmere' WHERE sku = 'CAB-MNM-0079';
UPDATE products SET door_count = 3, name = 'Boss 135x220 Drawers Walnut' WHERE sku = 'CAB-MNM-0080';
UPDATE products SET door_count = 4, name = 'Boss 160x220 Drawers White' WHERE sku = 'CAB-MNM-0081';
UPDATE products SET door_count = 4, name = 'Boss 160x220 Drawers Cashmere' WHERE sku = 'CAB-MNM-0082';
UPDATE products SET door_count = 4, name = 'Boss 180x220 Walnut' WHERE sku = 'CAB-MNM-0083';
UPDATE products SET door_count = 3, name = 'Wardrobe BOSS STANDART 120 - Cashmere Gray' WHERE sku = 'CAB-MNM-0084';
UPDATE products SET door_count = 3, name = 'Rim 120 Wardrobe Hinged Cashmere' WHERE sku = 'CAB-MNM-0085';
UPDATE products SET door_count = 3, name = 'Rim 120 Wardrobe Hinged Walnut Select' WHERE sku = 'CAB-MNM-0086';
UPDATE products SET door_count = 4, name = 'Rim 160 Wardrobe Hinged White' WHERE sku = 'CAB-MNM-0087';
UPDATE products SET door_count = 4, name = 'Wardrobe BOSS STANDART 180 - Chinchilla Gray' WHERE sku = 'CAB-MNM-0088';
UPDATE products SET door_count = 2, name = 'Rim 80 Wardrobe Hinged White' WHERE sku = 'CAB-MNM-0089';
UPDATE products SET door_count = 4, name = 'Idea 180 Wardrobe Hinged with Drawers Cashmere' WHERE sku = 'CAB-MNM-0090';
UPDATE products SET door_count = 3, name = 'Idea 120 Wardrobe Hinged Cashmere' WHERE sku = 'CAB-MNM-0091';
UPDATE products SET door_count = 3, name = 'Idea 135 Wardrobe Hinged with Drawers White' WHERE sku = 'CAB-MNM-0092';
UPDATE products SET door_count = 2, name = 'Idea 80 Wardrobe Hinged with Drawers White' WHERE sku = 'CAB-MNM-0093';
UPDATE products SET door_count = 2, name = 'Idea 80 Wardrobe Hinged with Drawers Cashmere' WHERE sku = 'CAB-MNM-0094';
UPDATE products SET door_count = 2, name = 'Idea 90 Wardrobe Hinged with Drawers White' WHERE sku = 'CAB-MNM-0095';
UPDATE products SET door_count = 2, name = 'Idea 90 Wardrobe Hinged with Drawers Cashmere' WHERE sku = 'CAB-MNM-0096';
UPDATE products SET door_count = 3, name = 'Idea 120 Wardrobe Hinged White' WHERE sku = 'CAB-MNM-0097';
UPDATE products SET door_count = 3, name = 'Idea 120 Wardrobe Hinged with Drawers White' WHERE sku = 'CAB-MNM-0098';
UPDATE products SET door_count = 3, name = 'Idea 120 Wardrobe Hinged with Drawers Cashmere' WHERE sku = 'CAB-MNM-0099';
UPDATE products SET door_count = 3, name = 'Idea 135 Wardrobe Hinged White' WHERE sku = 'CAB-MNM-0100';
UPDATE products SET door_count = 3, name = 'Idea 135 Wardrobe Hinged Cashmere' WHERE sku = 'CAB-MNM-0101';
UPDATE products SET door_count = 3, name = 'Idea 135 Wardrobe Hinged with Drawers Cashmere' WHERE sku = 'CAB-MNM-0102';
UPDATE products SET door_count = 4, name = 'Idea 160 Wardrobe Hinged with Drawers White' WHERE sku = 'CAB-MNM-0103';
UPDATE products SET door_count = 4, name = 'Idea 160 Wardrobe Hinged with Drawers Cashmere' WHERE sku = 'CAB-MNM-0104';
UPDATE products SET door_count = 4, name = 'Idea 180 Wardrobe Hinged with Drawers White' WHERE sku = 'CAB-MNM-0105';
