UPDATE products SET door_count = 3, name = 'Cabinet BOSS 120 Cashmere' WHERE sku = 'CAB-MNM-0001';
UPDATE products SET door_count = 3, name = 'Rim 120 Cabinet Cashmere' WHERE sku = 'CAB-MNM-0002';
UPDATE products SET door_count = 3, name = 'Rim 120 Cabinet Walnut' WHERE sku = 'CAB-MNM-0003';
UPDATE products SET door_count = 4, name = 'Rim 160 Cabinet White' WHERE sku = 'CAB-MNM-0004';
UPDATE products SET door_count = 4, name = 'Boss 180 Chinchilla' WHERE sku = 'CAB-MNM-0005';
UPDATE products SET door_count = 2, name = 'Rim 80 Cabinet White' WHERE sku = 'CAB-MNM-0006';
UPDATE products SET door_count = 4, name = 'Rim 180 Cabinet Cashmere' WHERE sku = 'CAB-MNM-0007';
UPDATE products SET door_count = 4, name = 'Rim 180 Cabinet Walnut' WHERE sku = 'CAB-MNM-0008';
UPDATE products SET door_count = 3, name = 'Boss 150 Chinchilla' WHERE sku = 'CAB-MNM-0009';
UPDATE products SET door_count = 4, name = 'Boss 180 Cashmere' WHERE sku = 'CAB-MNM-0010';
UPDATE products SET door_count = 2, name = 'Rim 90 Cabinet White' WHERE sku = 'CAB-MNM-0011';
UPDATE products SET door_count = 4, name = 'Rim 160 Cabinet Cashmere' WHERE sku = 'CAB-MNM-0012';
UPDATE products SET door_count = 4, name = 'Rim 160 Cabinet Walnut' WHERE sku = 'CAB-MNM-0013';
UPDATE products SET door_count = 3, name = 'Boss 150 Cashmere' WHERE sku = 'CAB-MNM-0014';
UPDATE products SET door_count = 3, name = 'Rim 135 Drawers Walnut' WHERE sku = 'CAB-MNM-0015';
UPDATE products SET door_count = 3, name = 'Rim 135 Cabinet Walnut' WHERE sku = 'CAB-MNM-0016';
UPDATE products SET door_count = 3, name = 'Rim 120 Drawers Walnut' WHERE sku = 'CAB-MNM-0017';
UPDATE products SET door_count = 2, name = 'Rim 90 Drawers Walnut' WHERE sku = 'CAB-MNM-0018';
UPDATE products SET door_count = 2, name = 'Rim 90 Cabinet Walnut' WHERE sku = 'CAB-MNM-0019';
UPDATE products SET door_count = 4, name = 'Rim 160 Drawers Cashmere' WHERE sku = 'CAB-MNM-0020';
UPDATE products SET door_count = 2, name = 'Rim 80 Drawers Walnut' WHERE sku = 'CAB-MNM-0021';
UPDATE products SET door_count = 2, name = 'Rim 80 Cabinet Walnut' WHERE sku = 'CAB-MNM-0022';
UPDATE products SET door_count = 4, name = 'Rim 180 Drawers Cashmere' WHERE sku = 'CAB-MNM-0025';
UPDATE products SET door_count = 4, name = 'Rim 180 Drawers White' WHERE sku = 'CAB-MNM-0026';
UPDATE products SET door_count = 4, name = 'Rim 180 Cabinet White' WHERE sku = 'CAB-MNM-0027';
UPDATE products SET door_count = 2, name = 'Rim 90 Drawers Cashmere' WHERE sku = 'CAB-MNM-0028';
UPDATE products SET door_count = 4, name = 'Rim 160 Drawers White' WHERE sku = 'CAB-MNM-0029';
UPDATE products SET door_count = 3, name = 'Rim 135 Drawers Cashmere' WHERE sku = 'CAB-MNM-0030';
UPDATE products SET door_count = 3, name = 'Rim 135 Drawers White' WHERE sku = 'CAB-MNM-0031';
UPDATE products SET door_count = 3, name = 'Rim 135 Cabinet Cashmere' WHERE sku = 'CAB-MNM-0032';
UPDATE products SET door_count = 3, name = 'Rim 135 Cabinet White' WHERE sku = 'CAB-MNM-0033';
UPDATE products SET door_count = 3, name = 'Rim 120 Drawers Cashmere' WHERE sku = 'CAB-MNM-0034';
UPDATE products SET door_count = 3, name = 'Rim 120 Drawers White' WHERE sku = 'CAB-MNM-0035';
UPDATE products SET door_count = 3, name = 'Rim 120 Cabinet White' WHERE sku = 'CAB-MNM-0036';
UPDATE products SET door_count = 2, name = 'Rim 90 Drawers White' WHERE sku = 'CAB-MNM-0037';
UPDATE products SET door_count = 2, name = 'Rim 90 Cabinet Cashmere' WHERE sku = 'CAB-MNM-0038';
UPDATE products SET door_count = 2, name = 'Rim 80 Drawers Cashmere' WHERE sku = 'CAB-MNM-0039';
UPDATE products SET door_count = 2, name = 'Rim 80 Drawers White' WHERE sku = 'CAB-MNM-0040';
UPDATE products SET door_count = 2, name = 'Rim 80 Cabinet Cashmere' WHERE sku = 'CAB-MNM-0041';
UPDATE products SET door_count = 4, name = 'Rim 160 Drawers Walnut' WHERE sku = 'CAB-MNM-0042';
UPDATE products SET door_count = 3, name = 'Boss 120x220 Drawers White' WHERE sku = 'CAB-MNM-0048';
UPDATE products SET door_count = 2, name = 'Boss 80x220 White' WHERE sku = 'CAB-MNM-0049';
UPDATE products SET door_count = 2, name = 'Boss 80x220 Drawers White' WHERE sku = 'CAB-MNM-0050';
UPDATE products SET door_count = 2, name = 'Boss 80x220 Drawers Cashmere' WHERE sku = 'CAB-MNM-0051';
UPDATE products SET door_count = 2, name = 'Boss 80x220 Drawers Walnut' WHERE sku = 'CAB-MNM-0052';
UPDATE products SET door_count = 3, name = 'Boss 135x220 White' WHERE sku = 'CAB-MNM-0053';
UPDATE products SET door_count = 3, name = 'Boss 135x220 Cashmere' WHERE sku = 'CAB-MNM-0054';
UPDATE products SET door_count = 3, name = 'Boss 135x220 Walnut' WHERE sku = 'CAB-MNM-0055';
UPDATE products SET door_count = 2, name = 'Boss 80x220 Cashmere' WHERE sku = 'CAB-MNM-0056';
UPDATE products SET door_count = 4, name = 'Boss 180x220 Drawers Cashmere' WHERE sku = 'CAB-MNM-0057';
